// <auto-generated />
using System;
using CoreMonthlyevidence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CoreMonthlyevidence.Migrations
{
    [DbContext(typeof(MyDBContext))]
    partial class MyDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CoreMonthlyevidence.Models.Department", b =>
                {
                    b.Property<string>("departmentid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("departmentlocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("departmentname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("departmentid");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("CoreMonthlyevidence.Models.Student", b =>
                {
                    b.Property<string>("studentid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<string>("departmentid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("picture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("studentname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("studentid");

                    b.HasIndex("departmentid");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("CoreMonthlyevidence.Models.Student", b =>
                {
                    b.HasOne("CoreMonthlyevidence.Models.Department", "department")
                        .WithMany("Students")
                        .HasForeignKey("departmentid");

                    b.Navigation("department");
                });

            modelBuilder.Entity("CoreMonthlyevidence.Models.Department", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
